import pandas as pd

def mock_worldcup_matches() -> pd.DataFrame:
    data = [
        {
            "match_id": "mock-1",
            "home": "Argentina",
            "away": "Algeria",
            "group": "J",
            "date_utc": "2026-06-17T01:00:00Z",
            "venue": "Kansas City Stadium",
            "status": "Jugado",
            "home_goals": 3,
            "away_goals": 0,
            "source": "mock",
        },
        {
            "match_id": "mock-2",
            "home": "France",
            "away": "Senegal",
            "group": "I",
            "date_utc": "2026-06-17T00:00:00Z",
            "venue": "New York New Jersey Stadium",
            "status": "Jugado",
            "home_goals": 3,
            "away_goals": 1,
            "source": "mock",
        },
        {
            "match_id": "mock-3",
            "home": "Portugal",
            "away": "Congo DR",
            "group": "K",
            "date_utc": "2026-06-17T17:00:00Z",
            "venue": "Houston Stadium",
            "status": "Jugado",
            "home_goals": 1,
            "away_goals": 1,
            "source": "mock",
        },
        {
            "match_id": "mock-4",
            "home": "England",
            "away": "Croatia",
            "group": "L",
            "date_utc": "2026-06-17T20:00:00Z",
            "venue": "Dallas Stadium",
            "status": "Próximo",
            "home_goals": None,
            "away_goals": None,
            "source": "mock",
        },
        {
            "match_id": "mock-5",
            "home": "Ghana",
            "away": "Panama",
            "group": "L",
            "date_utc": "2026-06-17T23:00:00Z",
            "venue": "Toronto Stadium",
            "status": "Próximo",
            "home_goals": None,
            "away_goals": None,
            "source": "mock",
        },
        {
            "match_id": "mock-6",
            "home": "Uzbekistan",
            "away": "Colombia",
            "group": "K",
            "date_utc": "2026-06-18T02:00:00Z",
            "venue": "Mexico City Stadium",
            "status": "Próximo",
            "home_goals": None,
            "away_goals": None,
            "source": "mock",
        },
    ]
    return pd.DataFrame(data)
